drop table if exists scene_object cascade;
drop table if exists scene cascade;
drop table if exists robot_state cascade;
drop table if exists object cascade;
drop table if exists object_class_attribute cascade;
drop table if exists object_class_attribute_type cascade;
drop table if exists object_group cascade;
drop table if exists object_class cascade;
drop table if exists object_size cascade;
drop table if exists object_shape cascade;
drop table if exists point_of_interest cascade;
drop table if exists region cascade;
drop table if exists object_class cascade;
drop table if exists object_label cascade;
drop table if exists object_class_label cascade;
drop table if exists object_relationship cascade;
drop table if exists object_relationship_type cascade;
drop table if exists object_class_features cascade;
drop table if exists object_sub_class cascade;
drop table if exists object_sub_class_features cascade;
drop table if exists agent_object cascade;
drop table if exists agent_attribute cascade;
drop table if exists agent_attribute_type cascade;
drop table if exists agent_feature cascade;
drop table if exists agent_feature_type cascade;
drop table if exists agent_speech cascade;
drop table if exists agent cascade;
drop table if exists app_info cascade;
DROP TABLE IF EXISTS action_type CASCADE;
DROP TABLE IF EXISTS robot_goals cascade;
DROP TABLE IF EXISTS agent_location CASCADE;
drop view if exists v_cur_object;
drop view if exists v_scene;
drop view if exists v_recent_scene;
drop function if exists update_object_region;
drop function if exists can_see;

