export COMMAND.qdeal = qdeal

export SOURCES.qdeal	= \
	delink.cc \
	qdeal.cc \
	qdeal_options.cc

export BASES.qdeal	= $(basename $(SOURCES.qdeal))
export OBJECTS.qdeal	= $(addsuffix .o,$(BASES.qdeal))

.PHONY:	all.qdeal
all.qdeal: $(COMMAND.qdeal) 

$(COMMAND.qdeal): $(OBJECTS.qdeal) $(BIG_LIBRARY)
	$(CXX) $(LDFLAGS) -o $(COMMAND.qdeal) $(OBJECTS.qdeal) -lnsl -ldl  $(BIG_LIBRARY)

.PHONY: install.qdeal
install.qdeal: /home/blinky/roboworkspace/src/PLANNING/teleor/qp10.10/bin/$(COMMAND.qdeal)

/home/blinky/roboworkspace/src/PLANNING/teleor/qp10.10/bin/$(COMMAND.qdeal): $(COMMAND.qdeal)
	/usr/bin/install -c $(COMMAND.qdeal) /home/blinky/roboworkspace/src/PLANNING/teleor/qp10.10/bin

.PHONY:	clean.qdeal
clean.qdeal:
	$(RM) $(OBJECTS.qdeal) $(COMMAND.qdeal) Makefile.qdeal


