export COMMAND.qa = qa

export SOURCES.qa	= \
	code_block.cc \
	qa.cc \
	qa_options.cc 

export BASES.qa	 = $(basename $(SOURCES.qa))
export OBJECTS.qa= $(addsuffix .o,$(BASES.qa))

export GENERATED.qa = qa.cc lexer.cc

.PHONY: all.qa
all.qa: $(COMMAND.qa)

$(COMMAND.qa): $(OBJECTS.qa) $(BIG_LIBRARY)
	$(CXX) $(LDFLAGS) -o $(COMMAND.qa) $(OBJECTS.qa) -lnsl -ldl  $(BIG_LIBRARY)	

qa.cc: lexer.cc qa.y
	yacc -oqa.cc qa.y

lexer.cc: qa.l
	: -olexer.cc qa.l

qa.o: qa.cc
	$(CXX) $(QACXXFLAGS) -c -o qa.o qa.cc
lexer.o: lexer.cc
	$(CXX) $(QACXXFLAGS) -c -o lexer.o lexer.cc

.PHONY: install.qa
install.qa: /home/blinky/roboworkspace/src/PLANNING/teleor/qp10.10/bin/$(COMMAND.qa)

/home/blinky/roboworkspace/src/PLANNING/teleor/qp10.10/bin/$(COMMAND.qa): $(COMMAND.qa)
	/usr/bin/install -c $(COMMAND.qa) /home/blinky/roboworkspace/src/PLANNING/teleor/qp10.10/bin

.PHONY:	clean.qa
clean.qa:
	$(RM) $(OBJECTS.qa) $(COMMAND.qa) Makefile.qa


