#
# Makefile for "qod"
#
export COMMAND.qod = qod

export SOURCES.qod = qod.cc

BASES.qod	= $(basename $(SOURCES.qod))
OBJECTS.qod	= $(addsuffix .o,$(BASES.qod))

export GENERATED.qod =

.PHONY:	all.qod
all.qod:	$(COMMAND.qod)

$(COMMAND.qod): $(OBJECTS.qod) $(LIBRARY.library) $(LIBRARY.thread)
	$(CXX) $(LDFLAGS) -o $(COMMAND.qod) $(OBJECTS.qod) -lnsl -ldl  $(LIBRARY.library) $(LIBRARY.thread)

.PHONY: install.qod
install.qod: /home/blinky/roboworkspace/src/PLANNING/teleor/qp10.10/bin/$(COMMAND.qod)

/home/blinky/roboworkspace/src/PLANNING/teleor/qp10.10/bin/$(COMMAND.qod): $(COMMAND.qod)
	/usr/bin/install -c $(COMMAND.qod) /home/blinky/roboworkspace/src/PLANNING/teleor/qp10.10/bin

.PHONY: clean.qod
clean.qod:
	$(RM) $(OBJECTS.qod) $(COMMAND.qod) Makefile.qod


